---
- hosts: all
  gather_facts: false
  become: true

  vars:
    chefdk_url: https://packages.chef.io/stable/ubuntu/12.04/chefdk_1.0.3-1_amd64.deb

    # https://docs.puppet.com/puppet/latest/reference/puppet_collections.html#apt-based-systems
    puppet_url: https://apt.puppetlabs.com/puppetlabs-release-pc1-trusty.deb

  tasks:
    - name: Only run "update_cache=yes" if the last one is more than 3600 seconds ago
      apt:
        update_cache: yes
        cache_valid_time: 3600

    - name: install remote debs (puppet and chefdk)
      apt:
        deb: "{{ item }}"
      with_items:
           - "{{ chefdk_url }}"
           - "{{ puppet_url }}"

    - name: Install list of packages
      apt: name={{item}} state=installed
      with_items:
           - python-dev 
           - python-pip
           - libffi-dev
           - vim
           - rubygems-integration
           - puppet

    - pip: name=virtualenv state=present

    - name: Manually create virtualenv
      command: virtualenv /home/vagrant/venv creates="/home/vagrant/venv"

    - name: Install pip packages
      pip: name={{item}} state=present  virtualenv=/home/vagrant/venv
      with_items:
           - ansible
           - pysphere
           - awscli
           - dopy
           - salt

    - template: 
        src: templates/vimrc 
        dest: /home/vagrant/.vimrc 
        owner: vagrant 
        group: vagrant 
      with_items:
        - { src: 'templates/vimrc', dest: '/home/vagrant/.vimrc' }
        - { src: 'templates/bash_profile', dest: '/home/vagrant/.bash_profile' }
        - { src: 'templates/gemrc', dest: '/home/vagrant/.gemrc' }
