export AWS_ACCESS_KEY_ID={{ aws_access_key_id }}
export AWS_SECRET_ACCESS_KEY={{ aws_secret_access_key }}

export DO_API_TOKEN={{ do_api_token }}

export DME_AKEY={{ dme_akey }}
export DME_SKEY={{ dme_skey }}

export VCENTER_USERNAME={{ vcenter_username }}
export VCENTER_PASSWORD={{ vcenter_password }}
export VCENTER_HOSTNAME={{ vcenter_hostname }}

export LOGICMONITOR_USERNAME={{ logicmonitor_username }}
export LOGICMONITOR_PASSWORD={{ logicmonitor_password }}